# Generated by Django 4.1.7 on 2023-04-06 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_category_comment_watchitem_auction_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="auctions.category",
            ),
        ),
    ]
