# Generated by Django 4.1.7 on 2023-04-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_category_categoryitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="category",
        ),
    ]
