# Generated by Django 4.1.7 on 2023-04-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_auction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="auctions.categoryitem",
            ),
        ),
    ]
